In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.feature_extraction.text import CountVectorizer
count=CountVectorizer()

In [ ]:
import tensorflow as tf
tf.test.gpu_device_name()

''

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
df_train = pd.read_csv("/content/drive/My Drive/sentiment324/Train.csv", encoding='UTF-8')

In [ ]:
df_valid = pd.read_csv("/content/drive/My Drive/sentiment324/Valid.csv", encoding='UTF-8')

In [ ]:
df_test = pd.read_csv("/content/drive/My Drive/sentiment324/Test.csv", encoding='UTF-8')

In [ ]:
data = pd.concat([df_train,df_valid])
data.head()

text  label
0  I grew up (b. 1965) watching and loving the Th...      0
1  When I put this movie in my DVD player, and sa...      0
2  Why do people who do not know what a particula...      0
3  Even though I have great interest in Biblical ...      0
4  Im a die hard Dads Army fan and nothing will e...      1

In [ ]:
import keras
from matplotlib import pyplot as plt
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
X_train=data['text'].values
Y_train=data['label'].values
X_test=df_test['text'].values
Y_test=df_test['label'].values

In [ ]:
vocab_size=30000 #went for an average vocab size 
embedding_dimension=64 #high dimensions would result in finding better parameters for similarity 
max_length=120 #used a maximum length of 120 words
turnc='post'#preprocessing step for pad_sequences
oov_tok='<OOV>'#oov stands for out of vocabulary tokens

In [ ]:
tokenizer=Tokenizer(num_words=vocab_size,filters='''!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~¡¢£¤¦§¨«­®°³´·º»½¾¿ßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþğıōżאגויכלמןר–‘’“”…″₤★、''',oov_token=oov_tok)
tokenizer.fit_on_texts(X_train)
X=tokenizer.texts_to_sequences(X_train)
X_padded=pad_sequences(X,maxlen=max_length,padding='post',truncating=turnc)
X_test_seq=tokenizer.texts_to_sequences(X_test)
X_test_padded=pad_sequences(X_test_seq,maxlen=max_length,padding='post',truncating=turnc)


In [ ]:
import nltk
nltk.download('punkt')
import string
from nltk import word_tokenize
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
import re
def preprocessor(text):
             text=re.sub('<[^>]*>','',text)
             emojis=re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)',text)
             text=re.sub('[\W]+',' ',text.lower()) +\
                ' '.join(emojis).replace('-','')
             return text   



In [ ]:
data['text']=data['text'].apply(preprocessor)
df_test['text']=df_test['text'].apply(preprocessor)

In [ ]:
from nltk.stem.porter import PorterStemmer

porter=PorterStemmer()

In [ ]:
def tokenizer(text):
        return text.split()

In [ ]:
def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
stop=stopwords.words('english')
print(stop)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

count-based

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()


In [ ]:
y_train_c=data.label.values
x_train_c=vectorizer.fit_transform(data.text)

In [ ]:
y_test_c=df_test.label.values
x_test_c=vectorizer.fit_transform(df_test.text)

In [ ]:
type(y_test_c)

numpy.ndarray

In [ ]:
total_data = pd.concat([data,df_test])


In [ ]:
x_c=vectorizer.fit_transform(total_data.text)
y_c=total_data.label.values

In [ ]:
from sklearn.model_selection import train_test_split

x_train_c,x_test_c,y_train_c,y_test_c=train_test_split(x_c,y_c,random_state=1,test_size=0.2,shuffle=False)

In [ ]:
from sklearn.linear_model import LogisticRegressionCV

clf=LogisticRegressionCV(cv=6,scoring='accuracy',random_state=0,n_jobs=-1,verbose=3,max_iter=500).fit(x_train_c,y_train_c)



[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed: 14.3min remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed: 14.3min finished


In [ ]:

y_pred_c = clf.predict(x_test_c)


In [ ]:
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test_c, y_pred_c))

Accuracy: 0.8937


In [ ]:
clf.fit(x_test_c,y_pred_c)
print(clf.coef_) #决策函数中的特征系数 :w1,w2....wn
print(clf.intercept_)

def x2(x1):
    print('coef_:',clf.coef_ ,clf.coef_[0][0])
    print("intercept_:",clf.intercept_)
    print("coef_ shape:",clf.coef_.shape)
    print("intercept_shape:",clf.intercept_.shape)
    print("classes_:",clf.classes_)
    return (-clf.coef_[0][0] * x1 - clf.intercept_[0]) / clf.coef_[0][1]

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:  3.8min remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:  3.8min finished


[[ 0.03440213 -0.31158847  0.         ...  0.          0.
   0.        ]]
[0.33330075]


In [ ]:
print(x_test_c.data)

[ 1 13 24 ...  1  1  2]


In [ ]:
X1 = x_test_c[y_pred_c == 0].data
X2 = x_test_c[y_pred_c == 1].data

print(X1)
 
plt.scatter(X1,x2(X1),c='blue')
plt.scatter(X2,x2(X2),c='red')
 
x1_plot = np.linspace(0, 1,100)
print(x1_plot)
x2_plot = x2(x1_plot)
plt.plot(x1_plot, x2_plot)
 
plt.show()

[ 1 13 24 ...  1  1  2]


NameError: ignored

In [ ]:
from sklearn.linear_model import SGDClassifier
clf= SGDClassifier(loss='hinge', penalty='l2', alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=0.001, shuffle=True, verbose=0, epsilon=0.1, n_jobs=None, random_state=None, learning_rate='optimal', eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, class_weight=None, warm_start=False, average=False)
clf.fit(x_train_c, y_train_c)
y_pred_c_svm = clf.predict(x_test_c)

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test_c, y_pred_c_svm))

Accuracy: 0.8873


In [ ]:
from sklearn.linear_model import SGDClassifier
clf= SGDClassifier(loss='log', penalty='l2', alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=0.001, shuffle=True, verbose=0, epsilon=0.1, n_jobs=None, random_state=None, learning_rate='optimal', eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, class_weight=None, warm_start=False, average=False)
clf.fit(x_train_c, y_train_c)
y_pred_c_log = clf.predict(x_test_c)

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test_c_log, y_pred_c_log))

Accuracy: 0.8915


tf-idf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer(strip_accents=None,lowercase=False,preprocessor=None,tokenizer=tokenizer_porter,use_idf=True,norm='l2',smooth_idf=True)

In [ ]:
total_data = pd.concat([data,df_test])

In [ ]:
y_train=data.label.values
x_train=tfidf.fit_transform(data.text)
print(x_train)

  (0, 32754)	0.11136137541182121
  (0, 20576)	0.1007913171488499
  (0, 29660)	0.07078355781412801
  (0, 59506)	0.18271620047317594
  (0, 53520)	0.3194671148834443
  (0, 29173)	0.13109887234183829
  (0, 38493)	0.15445408099747013
  (0, 51297)	0.08938904762466932
  (0, 10044)	0.02211678151754951
  (0, 1877)	0.07621512582234409
  (0, 38979)	0.053817484949865
  (0, 51129)	0.0822651928133281
  (0, 11544)	0.0914125507642068
  (0, 52693)	0.09292552855136146
  (0, 65815)	0.09030690964182514
  (0, 22354)	0.025156588453970504
  (0, 67434)	0.059399163199828124
  (0, 29289)	0.10748373130507594
  (0, 13652)	0.05428003862693786
  (0, 66378)	0.06333796909293808
  (0, 11586)	0.10043981693101815
  (0, 17503)	0.047555659519268545
  (0, 30506)	0.018698541666331222
  (0, 27384)	0.05978392336119744
  (0, 55831)	0.046953336230256125
  :	:
  (44999, 5176)	0.06312198551863006
  (44999, 41349)	0.03675340376356455
  (44999, 3175)	0.04288346407442206
  (44999, 11726)	0.03825641540434302
  (44999, 27015)	0.034678

In [ ]:
y_test=df_test.label.values
x_test=tfidf.fit_transform(df_test.text)
print(x_test)

  (0, 8237)	0.035896167941760336
  (0, 8973)	0.06929490680531085
  (0, 11936)	0.05398597850629143
  (0, 2105)	0.07142815626270224
  (0, 6565)	0.04769308452128664
  (0, 22688)	0.031220942361709664
  (0, 387)	0.04168918544094365
  (0, 3879)	0.061857494960860994
  (0, 9040)	0.055214163865217845
  (0, 22961)	0.07778805365906981
  (0, 4544)	0.06391914956410143
  (0, 2457)	0.04894245430640991
  (0, 1120)	0.057796123063260256
  (0, 26375)	0.029297949601728615
  (0, 17560)	0.061857494960860994
  (0, 9380)	0.06995796395415449
  (0, 10953)	0.03765550940948394
  (0, 17358)	0.02792770819922486
  (0, 22026)	0.06929490680531085
  (0, 22057)	0.05427953619140198
  (0, 24062)	0.07412363948868834
  (0, 5626)	0.07641617616770298
  (0, 25552)	0.0864930393579534
  (0, 21963)	0.05067485370086813
  (0, 5349)	0.051323942363543706
  :	:
  (4999, 19481)	0.06126245875473251
  (4999, 1607)	0.03324407019288031
  (4999, 12442)	0.07022570813167972
  (4999, 26594)	0.028519236762664876
  (4999, 25731)	0.08577377167274

In [ ]:
x=tfidf.fit_transform(total_data.text)
y=total_data.label.values

逻辑回归要求必须训练集和测试集一般多

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.2,shuffle=False)

逻辑回归CV

In [ ]:
from sklearn.linear_model import LogisticRegressionCV

clf=LogisticRegressionCV(cv=6,scoring='accuracy',random_state=0,n_jobs=-1,verbose=3,max_iter=500).fit(x_train,y_train)



[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:  8.2min remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:  8.2min finished


In [ ]:
y_pred = clf.predict(x_test)

In [ ]:
y_pred.shape

(10000,)

In [ ]:
x_test.shape

(10000, 73814)

In [ ]:
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8995


In [ ]:
clf.fit(x_test,y_pred)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:  1.6min remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:  1.6min finished


LogisticRegressionCV(Cs=10, class_weight=None, cv=6, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=500, multi_class='auto', n_jobs=-1, penalty='l2',
                     random_state=0, refit=True, scoring='accuracy',
                     solver='lbfgs', tol=0.0001, verbose=3)

In [ ]:

print(clf.coef_) #决策函数中的特征系数 :w1,w2....wn
print(clf.intercept_)

[[-0.9223898   0.52038492  0.91669642 ...  0.          0.
   0.        ]]
[0.13467756]


In [ ]:
clf.coef_[0]=clf.coef_[0].reshape((73814,))

In [ ]:
print(y_pred.data)

[0 0 0 ... 0 0 0]


In [ ]:
print(x_test.data)


[0.17716975 0.08303108 0.08011151 ... 0.06156818 0.0405765  0.02436182]


In [ ]:
table1 = np.array(x_test)
table1[:,0]


IndexError: ignored

In [ ]:
def x2(x1):
    print('coef_:',clf.coef_ ,clf.coef_[0][0])
    print("intercept_:",clf.intercept_)
    print("coef_ shape:",clf.coef_.shape)
    print("intercept_shape:",clf.intercept_.shape)
    print("classes_:",clf.classes_)
    return (-clf.coef_[0][0] * x1 - clf.intercept_[0]) / clf.coef_[0][1]

In [ ]:

X1 = x_test[y_pred == 0]
X2 = x_test[y_pred == 1]
 
plt.scatter(X2.data,c='blue')
plt.scatter(X1,c='red')
 
x1_plot = np.linspace(0, 1,100)
print(x1_plot)
x2_plot = x2(x1_plot)
plt.plot(x1_plot, x2_plot)
 
plt.show()

TypeError: ignored

In [ ]:
X1 = x_test[y_pred == 0]
X2 = x_test[y_pred == 1]
b=[i[0] for i in X1]
print(b)

[<1x73814 sparse matrix of type '<class 'numpy.float64'>'
	with 212 stored elements in Compressed Sparse Row format>, <1x73814 sparse matrix of type '<class 'numpy.float64'>'
	with 104 stored elements in Compressed Sparse Row format>, <1x73814 sparse matrix of type '<class 'numpy.float64'>'
	with 39 stored elements in Compressed Sparse Row format>, <1x73814 sparse matrix of type '<class 'numpy.float64'>'
	with 147 stored elements in Compressed Sparse Row format>, <1x73814 sparse matrix of type '<class 'numpy.float64'>'
	with 93 stored elements in Compressed Sparse Row format>, <1x73814 sparse matrix of type '<class 'numpy.float64'>'
	with 95 stored elements in Compressed Sparse Row format>, <1x73814 sparse matrix of type '<class 'numpy.float64'>'
	with 172 stored elements in Compressed Sparse Row format>, <1x73814 sparse matrix of type '<class 'numpy.float64'>'
	with 122 stored elements in Compressed Sparse Row format>, <1x73814 sparse matrix of type '<class 'numpy.float64'>'
	with 241

In [ ]:
def x2(x1):
    return (-clf.coef_[0] * x1 - clf.interception_)/clf.coef_[1]
x1_plot = np.linspace(4,8,1000)

x2_plot = x2(x1_plot)

plt.plot(x1_plot,x2_plot)
plt.scatter(X[y==0,0],X[y==0,1],color='r')
plt.scatter(X[y==1,0],X[y==1,1],color='b')
plt.show()

ValueError: ignored

In [ ]:
clf.fit(x_test, y_pred)
# 定义求X2的函数
def X2(X1):
	return (-clf.intercept_ - clf.coef_[0] * (X1)) / clf.coef_[1]

# 构建X1
X1 = np.linspace(4, 8, 1000)
X2 = X2(X1)

plt.scatter(X[y==0, 0], X[y==0, 1], color='r')
plt.scatter(X[y==1, 0], X[y==1, 1], color='b')
plt.plot(X1, X2)
plt.show()

ValueError: ignored

In [ ]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [ ]:
X1 = x_test[y_pred == 0]
X2 = x_test[y_pred == 1]
 
plt.scatter(X2['x1'],X2['x2'],c='blue')
plt.scatter(X1['x1'],X1['x2'],c='red')
 
x1_plot = np.linspace(0, 1,100)
print(x1_plot)
x2_plot = x2(x1_plot)
plt.plot(x1_plot, x2_plot)
 
plt.show()


IndexError: ignored

In [ ]:
comments = pd.Series(df_test["text"])
comments = vectorizer.transform(comments)
y_pred = model.predict_classes(comments)
nn_cm = metrics.confusion_matrix(test["label"],y_pred)
print(nn_cm)
# calculate the fpr and tpr for all thresholds of the classification
probs = model.predict_proba(x_valid_count)
preds = probs[:,:]
fpr, tpr, threshold = metrics.roc_curve(test["label"], y_pred)
roc_auc = metrics.auc(fpr, tpr)
plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, 'b', label = 'AUC = %0.3f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

NameError: ignored

SGD（SVM）

In [ ]:
from sklearn.linear_model import SGDClassifier
clf= SGDClassifier(loss='hinge', penalty='l2', alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=0.001, shuffle=True, verbose=0, epsilon=0.1, n_jobs=None, random_state=None, learning_rate='optimal', eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, class_weight=None, warm_start=False, average=False)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [ ]:
y_test.shape

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8965


SGD（逻辑回归）

In [ ]:
from sklearn.linear_model import SGDClassifier
clf= SGDClassifier(loss='log', penalty='l2', alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=0.001, shuffle=True, verbose=0, epsilon=0.1, n_jobs=None, random_state=None, learning_rate='optimal', eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, class_weight=None, warm_start=False, average=False)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8826


In [ ]:
from sklearn import svm
clf= svm.SVC()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))